name: app_spark
description: >-
  Provides widgets and extensions to improve app development
version: 1.0.1-alpha
repository: https://github.com/go-sparksoftware/app_spark
topics:
  - flutter
  - appdev
  - utils

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: MaterialSymbols
      fonts:
        - asset: lib/fonts/material_symbols/material_symbols_sharp.ttf